[package]
name = "resvg_svg_rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
resvg = "0.43.0"
usvg = { version = "0.43.0", default-features = false }
tiny-skia = "0.11.4"
reqwest = "0.12.7"

